apiVersion: v2
name: gatewayapi-securitypolicy-operator
description: A Helm chart to distribute the project gatewayapi-securitypolicy-operator
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: "https://example.com/icon.png"
