{{- if .Values.rbac.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: gatewayapi-securitypolicy-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gatewayapi-securitypolicy-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.controllerManager.serviceAccountName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end -}}
